repos:
  # api
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        types: [python]
      - id: ruff
        name: ruff-check
        entry: ruff check --fix
        types: [python]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
        name: terraform-fmt
        types: [terraform]

