repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff format
        entry: ruff format
        types: [python]
        language: system
      - id: ruff-check
        name: Ruff check
        entry: ruff check --fix
        types: [python]
        language: system
