services:
  postgres:
    container_name: postgres
    image: postgis/postgis:16-master
    # Disable some safety switches for a faster postgres: https://www.postgresql.org/docs/current/non-durability.html
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spock
      - PGUSER=postgres
      - PGPASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgres_data:
